/*
 * Doraku
 *
 * Doraku Backend API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hobbyapi

// Hobby struct defines info of hobby
type Hobby struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	NameEN      string `json:"nameEN"`
	Description string `json:"description"`
	Image       string `json:"image"`
	Group       int    `json:"group"`
}
