version: 2
jobs:
  build:
    docker:
      - image: mercari/appengine-go:1.11

    working_directory: /go/src/github.com/sh-miyoshi/doraku
    steps:
      - checkout

      - run:
          name: check environment
          command: go version
      - run:
          name: go get
          command: |
            cd backend
            GO111MODULE=on go get -u
      - run:
          name: run unit test
          command: |
            cd backend
            GO111MODULE=on go test -v ./...
      - run:
          name: deploy to GAE
          command: |
            if [ "x$DEV_SERVICE_ACCOUNT_CLIENT_EMAIL" != "x" ]; then
              echo $DEV_SERVICE_ACCOUNT_KEY > /tmp/secret.json
              sudo gcloud config set project dorkau-241004
              sudo gcloud auth activate-service-account $DEV_SERVICE_ACCOUNT_CLIENT_EMAIL --key-file /tmp/secret.json
              sudo gcloud services enable appengine.googleapis.com
              cd backend
              sudo gcloud app deploy --quiet
            fi
