/*
 * Doraku
 *
 * Doraku Backend API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hobby

import (
	"net/http"

	"github.com/sh-miyoshi/doraku/pkg/logger"
)

// GetHobbyHandler return lists of hobbies
func GetHobbyHandler(w http.ResponseWriter, r *http.Request) {
	logger.Info("call GetHobby method")

	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

// GetHobbyByGroupNoHandler return lists of hobbies filtered by groupNo
func GetHobbyByGroupNoHandler(w http.ResponseWriter, r *http.Request) {
	logger.Info("call GetHobby method")

	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

// GetHobbyByIDHandler return the hobby determined by ID
func GetHobbyByIDHandler(w http.ResponseWriter, r *http.Request) {
	logger.Info("call GetHobby method")

	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
