/*
 * Doraku
 *
 * Doraku Backend API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hobby

import (
	"net/http"

	"github.com/sh-miyoshi/doraku/pkg/logger"
)

// GetHobby return lists of hobbies
func GetHobby(w http.ResponseWriter, r *http.Request) {
	logger.Info("call GetHobby method")

	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

// GetHobbyByGroupNo return lists of hobbies filtered by groupNo
func GetHobbyByGroupNo(w http.ResponseWriter, r *http.Request) {
	logger.Info("call GetHobby method")

	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

// GetHobbyByID return the hobby determined by ID
func GetHobbyByID(w http.ResponseWriter, r *http.Request) {
	logger.Info("call GetHobby method")

	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
