/*
 * Doraku
 *
 * Doraku Backend API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hobby

type Hobby struct {
	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	NameEN string `json:"name_EN,omitempty"`

	Description string `json:"description,omitempty"`

	Image string `json:"image,omitempty"`

	Group int32 `json:"group,omitempty"`
}
