swagger: '2.0'
info:
  description: Doraku Backend API
  version: 1.0.0
  title: Doraku
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
basePath: /api/v1
schemes:
  - http
paths:
  /hobby/all:
    get:
      tags:
        - hobby
      summary: get all hobby names
      description: get list of all hobby name
      produces:
        - application/json
      responses:
        '200':
          description: ok
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
  /hobby/today:
    get:
      tags:
        - hobby
      summary: get today's hobby
      description: get today's hobby
      produces:
        - application/json
      responses:
        '200':
          description: ok
          schema:
            type: string
  /hobby/recommended:
    get:
      tags:
        - hobby
      summary: get recommended hobby
      description: get recommended hobby
      parameters:
        - name: selects
          in: body
          required: true
          schema:
            properties:
              outdoor:
                type: boolean
              alone:
                type: boolean
              active:
                type: boolean
      responses:
        '200':
          description: ok
          schema:
            type: string
  '/hobby/details/{id}':
    get:
      tags:
        - hobby
      summary: get details of the hobby
      description: get details of the hobby
      produces:
        - application/json
      parameters:
        - name: id
          type: integer
          in: path
          description: id of the hobby
          required: true
      responses:
        '200':
          description: ok
          schema:
            $ref: '#/definitions/Hobby'
        '404':
          description: No such hobby
definitions:
  Hobby:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      nameEN:
        type: string
      description:
        type: string
      image:
        type: string
      groupInfo:
        type: string
