swagger: '2.0'
info:
  description: Doraku Backend API
  version: 1.0.0
  title: Doraku
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
basePath: /api/v1
schemes:
  - http
paths:
  /hobby:
    get:
      tags:
        - hobby
      summary: get all hobby
      description: get list of all hobby
      produces:
        - application/json
      responses:
        '200':
          description: ok
  '/hobby/id/{id}':
    get:
      tags:
        - hobby
      summary: get detail of hobby by ID
      description: Returns a hobby detail
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of hobby to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: ok
          schema:
            $ref: '#/definitions/Hobby'
        '400':
          description: invalid ID supplied
        '404':
          description: hobby not found
  '/hobby/group/{groupNo}':
    get:
      tags:
        - hobby
      summary: get hobby list by same group
      description: Returns list of hobby
      parameters:
        - name: groupNo
          in: path
          required: true
          type: integer
      responses:
        '200':
          description: ok
definitions:
  Hobby:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      name_EN:
        type: string
      description:
        type: string
      image:
        type: string
      group:
        type: integer
